[package]
name = "teos-common"
version = "0.0.1"
authors = ["Sergi Delgado Segura <sergi.delgado.s@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# General
hex = { version = "0.4.3", features = [ "serde" ] }
prost = "0.9"
serde = "1.0.130"
tonic = "0.6"

# Crypto
rand = "0.8.4"
chacha20poly1305 = "0.8.0"

# Bitcoin and Lightning
bitcoin = "0.27"
lightning = "0.0.105"

[build-dependencies]
tonic-build = "0.6"